JZ -  added Leaderboard Feature for totalWealth to be displayed in the desired format
ucsb-cs156-m23/proj-happycows-m23-10am-2 pull request #16
Opened 2023-08-19 22:24 UTC by jczhou02

Additionally, made changes to   [frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js]
closes issue #11   

![Screenshot (264)](https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/assets/102626158/48fd4946-0a93-4eed-b106-176c32485ed5)

2023-08-21 17:12 UTC, rockygao2020 commented on frontend/src/main/components/Leaderboard/LeaderboardTable.js
Code checks out with the required changes, and the tests make perfect sense.

2023-08-21 17:12 UTC, rockygao2020 submitted a review, later dismissed
Code checks out with the required changes, and the tests make perfect sense.

2023-08-22 01:36 UTC, pconrad requested changes
LGTM... but I suggest removing a few unnecessary comments, as well as right aligning the dollar amounts so that they all line up in the table column.

2023-08-22 01:36 UTC, pconrad commented on frontend/src/main/components/Leaderboard/LeaderboardTable.js
> +                return <span>{custom_wealth}</span>
If you do this, it should display right aligned, which makes more sense for currency.  

```suggestion
                return div style={{textAlign: "right"}}>{custom_wealth}</div>
```

2023-08-22 01:36 UTC, pconrad commented on frontend/src/main/components/Leaderboard/LeaderboardTable.js
> +            //this is the func to  can return custom tableCell
I suggest removing this comment.

2023-08-22 01:36 UTC, pconrad commented on frontend/src/main/components/Leaderboard/LeaderboardTable.js
> +            //you can convert total wealth data here
I suggest removing this comment
```suggestion
```

2023-08-22 01:36 UTC, pconrad commented on frontend/src/main/components/Leaderboard/LeaderboardTable.js
> +            //this is the func to  can return custom tableCell
```suggestion
```

2023-08-23 22:21 UTC, pconrad approved these changes
LGTM!

2023-08-23 22:22 UTC, merged