CC - removed purchase pop ups
ucsb-cs156-m23/proj-happycows-m23-10am-2 pull request #27
Opened 2023-08-22 20:06 UTC by cyrus895

removes "cow bought" pop up when purchasing a cow.

Depoyed on https://happycows-cyrus895.dokku-05.cs.ucsb.edu

For testing, Try buying a cow no pop up should appear

2023-08-22 21:19 UTC, rockygao2020 approved these changes
Looks good.

2023-08-22 22:54 UTC, chriscerie requested changes

2023-08-22 22:54 UTC, chriscerie commented on frontend/src/main/pages/PlayPage.js
> +
Don’t leave event handlers empty. If you don’t need them then just remove them.

2023-08-23 22:34 UTC, pconrad approved these changes
LGTM.  Chris has a point, but I think for this code base, it's better to leave the empty handlers so that future devs know where to put things.

2023-08-23 22:34 UTC, merged