JZ - CommonStats
ucsb-cs156-m23/proj-happycows-m23-10am-2 pull request #36
Opened 2023-08-24 07:13 UTC by jczhou02

closes #35

2023-08-24 23:38 UTC, kirrarista approved these changes
Looks good! Will look at it more thoroughly when the front end is up

2023-08-24 23:39 UTC, pconrad approved these changes
LGTM

2023-08-24 23:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/entities/CommonStats.java
> +    private LocalDateTime timestamp;
```suggestion
    @CreatedDate
    private LocalDateTime timestamp;
```

If we add this, with import:
```java
import org.springframework.data.annotation.CreatedDate;
```

then the field will be automatically populated with the correct value when you save a new record in the database.

2023-08-24 23:44 UTC, pconrad requested changes
see my comment

2023-08-25 09:17 UTC, rockygao2020 approved these changes
Looks good, tested Dokku after deleting databases

2023-08-25 21:24 UTC, pconrad approved these changes
LGTM!

2023-08-25 21:24 UTC, merged